package Frontera.Usuarios;

import Control.*;
import Frontera.FramePrincipal;
import Frontera.FramePrincipal;
import com.easycoffee.Usuario;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Diego Lopez Avila <dlopezav at unal.edu.co>
 */
public class PerfilUsuario extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProduccion
     */
    private int id;

    public PerfilUsuario(int ced) {
        initComponents();
        ControlUsuarios u = new ControlUsuarios();
        cedula.setText(String.valueOf(ced));
        Usuario x = u.obtenerUser(ced);
        this.id = ced;
        this.Name.setText(x.getNombre() + " " + x.getApellido());
        if(x.getImagen() != null){
        ImageIcon imagen = x.getImagen();
        Foto.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        actualizar = new javax.swing.JToggleButton();
        Foto = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 376));
        setMinimumSize(new java.awt.Dimension(900, 376));
        setPreferredSize(new java.awt.Dimension(900, 376));

        Name.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cédula:");

        cedula.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));

        actualizar.setBackground(new java.awt.Color(102, 0, 0));
        actualizar.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar imágen");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Name)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF", "jpg", "gif","png");
        j.setFileFilter(filter);
        String ruta;
        int ap = j.showOpenDialog(this);
        FileInputStream fi = null;
        Foto.setText("");
        if (ap == JFileChooser.APPROVE_OPTION) {
            ruta = j.getSelectedFile().getAbsolutePath();
            ImageIcon imagen = new ImageIcon(ruta);
            Foto.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(Foto.getWidth(), Foto.getHeight(), Image.SCALE_SMOOTH)));
            ControlUsuarios u = new ControlUsuarios();
            Usuario x = null;
            for (Usuario user : FramePrincipal.getSistem().getAdmin().getFinca().getAuxiliares()) {
                if (user.getCedula().intValue() == id) {
                    user.setImagen(imagen);
                    x = user;
                }
            }
            try {
                u.registrarFotoUsuario(x.getCedula().intValue(), ruta);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EditarAuxiliar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_actualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Name;
    private javax.swing.JToggleButton actualizar;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
