package Frontera.Administrativo;

import Frontera.FramePrincipal;
import Frontera.MenuAdministrativo;
import WebS.PrecioCafe;
import com.easycoffee.VentaCafe;
import java.awt.HeadlessException;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Vargas
 */
public class RegistrarVenta extends javax.swing.JPanel {

    private String[] unidades = {"Kg", "Lb", "Arrobas", "Cargas"};
    private String[] variedadesCafe = {"Pergamino (Seco)", "Pasilla", "Verde"};
    private int cedula;
    private VentaCafe venta;
    private double pergamino;   //Precio de Kg
    private double pasilla;     //Precio por Kg

    /**
     * Creates new form RegistrarVenta
     *
     * @param cedula: Cedula del Usuario en Curso
     */
    public RegistrarVenta(int cedula) {
        initComponents();
        verifyWebServiceConection();
        this.cedula = cedula;
        this.venta = new VentaCafe();

        try {
            this.pasilla = Double.parseDouble(PrecioCafe.getInstance().getPrecioPasillaFinca().replace("$", "").replace(".", "")) / 11.339;
            this.pergamino = Double.parseDouble(PrecioCafe.getInstance().getPrecioInternoRef().replace("$", "").replace(".", "")) / 125;
        } catch (IOException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        ;

        unidadMedida.removeAllItems();
        for (int i = 0; i < unidades.length; i++) {
            unidadMedida.addItem(unidades[i]);
        }
        variedadCafe.removeAllItems();
        for (int i = 0; i < variedadesCafe.length; i++) {
            variedadCafe.addItem(variedadesCafe[i]);
        }
        cambiarPreciosReferencia(pergamino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidadVendida = new javax.swing.JTextField();
        precioVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        variedadCafe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        unidadMedida = new javax.swing.JComboBox<>();
        registrarVenta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        precioReferencia = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 376));
        setMinimumSize(new java.awt.Dimension(900, 376));
        setPreferredSize(new java.awt.Dimension(900, 376));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar venta de café");

        cantidadVendida.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        precioVenta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Variedad de Venta:");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad Vendida:");

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio de Venta:");

        variedadCafe.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        variedadCafe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        variedadCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variedadCafeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unidad:");

        unidadMedida.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        unidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        unidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadMedidaActionPerformed(evt);
            }
        });

        registrarVenta.setBackground(new java.awt.Color(153, 51, 0));
        registrarVenta.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        registrarVenta.setForeground(new java.awt.Color(255, 255, 255));
        registrarVenta.setText("Registrar");
        registrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio de Referencia:");

        precioReferencia.setEditable(false);
        precioReferencia.setBackground(new java.awt.Color(0, 102, 0));
        precioReferencia.setForeground(new java.awt.Color(255, 255, 255));
        precioReferencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioReferencia.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        precioReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioReferenciaActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(102, 0, 0));
        cancelar.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Por favor ingrese los datos de la venta solicitados a continuación, seguido de presionar el botón \"Registrar\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(registrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(variedadCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadVendida, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(precioReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(535, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(variedadCafe)
                    .addComponent(precioReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadVendida, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarVenta))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void variedadCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variedadCafeActionPerformed
        switch (variedadCafe.getSelectedIndex()) {
            case 0:     //Pergamino(seco)
                cambiarPreciosReferencia(pergamino);
                break;
            case 1:     //Pasilla
                cambiarPreciosReferencia(pasilla);
                break;
            case 2:     //Verde
                JOptionPane.showMessageDialog(null, "Se recomienda la venta de Café Pergamino (Seco)");
                precioReferencia.setText("No Disponible");
                break;
        }
    }//GEN-LAST:event_variedadCafeActionPerformed

    private void registrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentaActionPerformed
    }//GEN-LAST:event_registrarVentaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        FramePrincipal.cambiarPanel376(new MenuAdministrativo(cedula));
        System.gc();
    }//GEN-LAST:event_cancelarActionPerformed

    private void precioReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioReferenciaActionPerformed
    }//GEN-LAST:event_precioReferenciaActionPerformed

    private void unidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadMedidaActionPerformed
        DecimalFormat format = new DecimalFormat("$ ###,###,###.##  COP");
        switch (variedadCafe.getSelectedIndex()) {
            case 0:     //Pergamino(seco)
                cambiarPreciosReferencia(pergamino);
                break;
            case 1:     //Pasilla
                cambiarPreciosReferencia(pasilla);
                break;
            case 2:     //Verde
//                JOptionPane.showMessageDialog(null, "Se recomienda la venta de Café Pergamino (Seco)");
                precioReferencia.setText("No Disponible");
                break;
        }
    }//GEN-LAST:event_unidadMedidaActionPerformed

    private void cambiarPreciosReferencia(double precio) {
        DecimalFormat format = new DecimalFormat("$ ###,###,###.##  COP");
        switch (unidadMedida.getSelectedIndex()) {
            case 0:     //Kilogramos
                precioReferencia.setText(format.format(precio));
                break;
            case 1:     //Libras
                precioReferencia.setText(format.format(precio / 2.205));
                break;
            case 2:     //Arrobas
                precioReferencia.setText(format.format(precio * 11.339));
                break;
            case 3:
                precioReferencia.setText(format.format(precio * 125));
                break;
        }
    }

    private void verifyWebServiceConection() {
        try {
            if (!PrecioCafe.getInstance().isCharged()) {
                JOptionPane.showMessageDialog(null, "Upps... Error al Intentar Cargar el Precio del Café, por favor verifica tu conexión a Internet e intenta nuevamente");
            }
        } catch (NullPointerException | IOException ex) {
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Upps... Error al Intentar Cargar el Precio del Café, por favor verifica tu conexión a Internet e intenta nuevamente");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidadVendida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField precioReferencia;
    private javax.swing.JTextField precioVenta;
    private javax.swing.JButton registrarVenta;
    private javax.swing.JComboBox<String> unidadMedida;
    private javax.swing.JComboBox<String> variedadCafe;
    // End of variables declaration//GEN-END:variables
}
