/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import javax.swing.JPanel;

/**
 *
 * @author Nivektakedown
 */
public class DoblePanel extends javax.swing.JPanel {

    /**
     * Creates new form doblePanel
     */
    public DoblePanel() {
        initComponents();
        cambiarPanel127(new RegistroFinca());
        cambiarPanel376(new RegistrarLote());
    }
    public static void cambiarPanel127(JPanel panel) {
        //fondo = new Fondo(panel, panel.fondo);
        panel.setOpaque(false);
        jPanel127.setVisible(false);
        jPanel127.removeAll();
        jPanel127.add(panel);
        jPanel127.setVisible(true);
    }
    public static void cambiarPanel376(JPanel panel) {
        //fondo = new Fondo(panel, panel.fondo);
        panel.setOpaque(false);
        jPanel376.setVisible(false);
        jPanel376.removeAll();
        jPanel376.add(panel);
        jPanel376.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel127 = new javax.swing.JPanel();
        jPanel376 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(900, 503));
        setMinimumSize(new java.awt.Dimension(900, 503));
        setPreferredSize(new java.awt.Dimension(900, 503));

        jPanel127.setMaximumSize(new java.awt.Dimension(900, 127));
        jPanel127.setMinimumSize(new java.awt.Dimension(900, 127));
        jPanel127.setPreferredSize(new java.awt.Dimension(900, 127));
        jPanel127.setLayout(new java.awt.BorderLayout());

        jPanel376.setMaximumSize(new java.awt.Dimension(900, 376));
        jPanel376.setMinimumSize(new java.awt.Dimension(900, 376));
        jPanel376.setPreferredSize(new java.awt.Dimension(900, 376));
        jPanel376.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel127, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel376, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel127, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel376, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel jPanel127;
    private static javax.swing.JPanel jPanel376;
    // End of variables declaration//GEN-END:variables
}
