package Frontera;

import Frontera.FramePrincipal;
import Frontera.FramePrincipal;
import Frontera.Usuarios.Ingreso;
import Frontera.Usuarios.PerfilUsuario;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Vargas
 */
public class MenuSeleccionAux extends javax.swing.JPanel {

    static String fondo = "../image/cafe.jpg";

    private int cedula;

    public MenuSeleccionAux(int cedula) {
        initComponents();
        this.cedula = cedula;
        this.ListaNotificaciones.removeAllItems();
        for (int i = 0; i < FramePrincipal.getSistem().getAdmin().getFinca().getLotes().size(); i++) {
            String s=FramePrincipal.getSistem().getAdmin().getFinca().getLotes().get(i).getFechaDesyerbado();
            String ss[]=s.split("/");
            Calendar c=Calendar.getInstance();
            c.set(Calendar.DATE, Integer.parseInt(ss[0]));
            c.set(Calendar.MONTH, Integer.parseInt(ss[1]));
            c.set(Calendar.YEAR, Integer.parseInt(ss[2]));
            c.add(Calendar.DATE, FramePrincipal.getSistem().getAdmin().getFinca().getLotes().get(i).getFrecDesyer());
            if(c.compareTo(Calendar.getInstance())<0){
                this.ListaNotificaciones.addItem("El lote "+i+" está listo para desyerbarse");
            }
        }
        this.ListaNotificaciones.setVisible(false);
        FramePrincipal.cambiarPanel127(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        produccion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        verPerfil = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        cerrar = new javax.swing.JButton();
        notific = new javax.swing.JButton();
        ListaNotificaciones = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(900, 127));
        setMinimumSize(new java.awt.Dimension(900, 127));
        setPreferredSize(new java.awt.Dimension(900, 127));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido A EasyCoffe App");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Por favor seleccione la Acción que desea realizar");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(700, 27));
        jToolBar1.setMinimumSize(new java.awt.Dimension(685, 27));
        jToolBar1.setPreferredSize(new java.awt.Dimension(685, 27));

        produccion.setBackground(new java.awt.Color(102, 0, 0));
        produccion.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        produccion.setForeground(new java.awt.Color(255, 255, 255));
        produccion.setText("Producción");
        produccion.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white)));
        produccion.setMaximumSize(new java.awt.Dimension(150, 27));
        produccion.setMinimumSize(new java.awt.Dimension(150, 27));
        produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionActionPerformed(evt);
            }
        });
        jToolBar1.add(produccion);
        jToolBar1.add(jSeparator1);

        verPerfil.setBackground(new java.awt.Color(102, 0, 0));
        verPerfil.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        verPerfil.setForeground(new java.awt.Color(255, 255, 255));
        verPerfil.setText("Ver Perfil");
        verPerfil.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white)));
        verPerfil.setMaximumSize(new java.awt.Dimension(150, 27));
        verPerfil.setMinimumSize(new java.awt.Dimension(150, 27));
        verPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPerfilActionPerformed(evt);
            }
        });
        jToolBar1.add(verPerfil);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator7);
        jToolBar1.add(jSeparator8);

        cerrar.setBackground(new java.awt.Color(0, 153, 153));
        cerrar.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("Cerrar sesión ");
        cerrar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), null));
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        notific.setBackground(new java.awt.Color(153, 102, 0));
        notific.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        notific.setForeground(new java.awt.Color(255, 255, 255));
        notific.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-alarma-50.png"))); // NOI18N
        notific.setText("Mostrar notificaciones");
        notific.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), null));
        notific.setMaximumSize(new java.awt.Dimension(190, 52));
        notific.setMinimumSize(new java.awt.Dimension(180, 52));
        notific.setPreferredSize(new java.awt.Dimension(210, 52));
        notific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificActionPerformed(evt);
            }
        });

        ListaNotificaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ListaNotificaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(notific, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ListaNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void verPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPerfilActionPerformed
        FramePrincipal.cambiarPanel376(new PerfilUsuario(cedula));
        verPerfil.setBackground(new Color(152, 51, 0));
        produccion.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_verPerfilActionPerformed

    private void produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionActionPerformed
        FramePrincipal.cambiarPanel376(new MenuProduccion(cedula));
        produccion.setBackground(new Color(152, 51, 0));
        verPerfil.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_produccionActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
       int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Confirmación", JOptionPane.YES_NO_OPTION);
       if(resp == JOptionPane.YES_OPTION){
        FramePrincipal.menuDoublePanel(false);
        FramePrincipal.cambiarPanel(new Ingreso());
        FramePrincipal.menuPanelPrincipal(true);
       }
    }//GEN-LAST:event_cerrarActionPerformed

    private void notificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificActionPerformed
        if(this.ListaNotificaciones.isVisible()==true)
            this.ListaNotificaciones.setVisible(false);
        else
            this.ListaNotificaciones.setVisible(true);
        FramePrincipal.cambiarPanel127(this);

    }//GEN-LAST:event_notificActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaNotificaciones;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton notific;
    private javax.swing.JButton produccion;
    private javax.swing.JButton verPerfil;
    // End of variables declaration//GEN-END:variables
}
