package Frontera;

import Frontera.EditFinca;
import Frontera.FramePrincipal;
import com.easycoffee.Lote;
import java.util.ArrayList;

/**
 *
 * @author Camilo Vargas
 */
public class MenuSeleccion extends javax.swing.JPanel {

    static String fondo = "../image/cafe.jpg";

    private int cedula;

    public MenuSeleccion(int cedula) {
        initComponents();
        this.cedula = cedula;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        usuarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        produccion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        finanzas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        estadisticas = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        estadisticas1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 127));
        setMinimumSize(new java.awt.Dimension(900, 127));
        setPreferredSize(new java.awt.Dimension(900, 127));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido A EasyCoffe App");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Por favor seleccione la Acción que desea realizar");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        usuarios.setBackground(new java.awt.Color(102, 0, 0));
        usuarios.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        usuarios.setForeground(new java.awt.Color(255, 255, 255));
        usuarios.setText("Gestión Usuarios");
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(usuarios);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator6);

        produccion.setBackground(new java.awt.Color(102, 0, 0));
        produccion.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        produccion.setForeground(new java.awt.Color(255, 255, 255));
        produccion.setText("Producción");
        produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionActionPerformed(evt);
            }
        });
        jToolBar1.add(produccion);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator5);

        finanzas.setBackground(new java.awt.Color(102, 0, 0));
        finanzas.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        finanzas.setForeground(new java.awt.Color(255, 255, 255));
        finanzas.setText("Administracion Contable");
        finanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finanzasActionPerformed(evt);
            }
        });
        jToolBar1.add(finanzas);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);

        estadisticas.setBackground(new java.awt.Color(102, 0, 0));
        estadisticas.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        estadisticas.setText("Reportes y Estadísticas");
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });
        jToolBar1.add(estadisticas);
        jToolBar1.add(jSeparator7);
        jToolBar1.add(jSeparator8);

        estadisticas1.setBackground(new java.awt.Color(102, 0, 0));
        estadisticas1.setFont(new java.awt.Font("Sitka Banner", 1, 16)); // NOI18N
        estadisticas1.setForeground(new java.awt.Color(255, 255, 255));
        estadisticas1.setText("Gestion Finca");
        estadisticas1.setFocusable(false);
        estadisticas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        estadisticas1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        estadisticas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticas1ActionPerformed(evt);
            }
        });
        jToolBar1.add(estadisticas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2)))
                .addContainerGap(359, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        FramePrincipal.cambiarPanel376(new MenuUsuarios(cedula));
    }//GEN-LAST:event_usuariosActionPerformed

    private void produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionActionPerformed
        FramePrincipal.cambiarPanel376(new MenuProduccion(cedula));
    }//GEN-LAST:event_produccionActionPerformed

    private void finanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finanzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finanzasActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadisticasActionPerformed

    private void estadisticas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticas1ActionPerformed
        FramePrincipal.cambiarPanel127(new EditFinca(cedula));
        FramePrincipal.cambiarPanel376(new RegistrarLote(new ArrayList<Lote>()));
    }//GEN-LAST:event_estadisticas1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estadisticas;
    private javax.swing.JButton estadisticas1;
    private javax.swing.JButton finanzas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton produccion;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
